name: SLSA Source Generator

on:
  release:
    types: [created]

jobs:
  provenance:
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_source_slsa3.yml@v2.0.0
